# docker-compose.yml
version: '3.8'

services:
    # PHP-FPM Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - laravel_network
        depends_on:
            - db

    # Nginx Service
    webserver:
        image: nginx:alpine
        container_name: laravel_webserver
        restart: unless-stopped
        ports:
            - "81:80"
            - "443:443"
        volumes:
            - teyojantra_data:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/ssl:/etc/nginx/ssl
        networks:
            - laravel_network
        depends_on:
            - app

    # MySQL Service
    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: tejoyantra
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: password
            MYSQL_USER: tejoyantra
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - "3307:3306"
        networks:
            - laravel_network

volumes:
    dbdata:
    teyojantra_data:

networks:
    laravel_network:
        driver: bridge
